version: '3'
services:
  web:
    build: .
    environment:
      FLASK_APP: 'flaskr'
      FLASK_ENV: 'development'
    ports:
    - "5000:5000"
    volumes:
    - .:/code
    depends_on:
    - db
  db:
    image: mysql
    restart: always
    environment:
      MYSQL_DATABASE: 'instant_messaging'
      MYSQL_USER: 'root'
      MYSQL_ROOT_PASSWORD: 'rootpassword'
    ports:
      - 3306:3306
    expose:
      - 3306
    volumes:
      - my-db:/var/lib/mysql
volumes:
  my-db:
